version: '3'
services:
  php:
    build: .docker/php
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  nginx:
    image: nginx
    depends_on:
      - php
    volumes:
      - ./app:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - PMA_HOST=mysql
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - '8081:80'