FROM php:8.1-fpm
WORKDIR '/app'

# Install selected extensions and other stuff
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git unzip mc nano
#RUN apt-get install -y npm

# MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer
RUN composer --version

