FROM php:8.1.7-fpm
WORKDIR '/app'

# Install selected extensions and other stuff
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git unzip mc nano libicu-dev gnupg2

# PHP Extention
RUN docker-php-ext-install pdo pdo_mysql intl

# Xdebug
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

#INSTALL APCU
RUN pecl install apcu && docker-php-ext-enable apcu
RUN echo "extension=apcu.so" > /usr/local/etc/php/php.ini
RUN echo "apc.enable_cli=1" > /usr/local/etc/php/php.ini
RUN echo "apc.enable=1" > /usr/local/etc/php/php.ini

#PHP OPcache
RUN docker-php-ext-install opcache

#PHP GD, ZIP for phpoffice
RUN apt-get install -y libzip-dev libpng-dev
RUN docker-php-ext-install zip
RUN docker-php-ext-install gd

#Install YARN
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer
RUN composer --version
